parallel-jobs = 1

[YouTube-Extended]
enabled = true
app-name = "RVX YouTube"
patches-source = "inotia00/revanced-patches"
cli-source = "inotia00/revanced-cli"
rv-brand = "ReVanced Extended"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"

[TikTok]
enabled = true
app-name = "RV Tiktok"
build-mode = "apk"
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"

[Spotify Ali]
enabled = true
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/spotify-ab/spotify-music-podcasts
